### ISSUE TITLE
flask 서버를 비동기 서버로 만들기

### ISSUE THREAD

**Issue by jaymores** [KSY97/sentiment-analysis-sns#4]
목표
- ㅁㅁㅁ 를 한다.

할일

- [ ] aaa 모듈 생성

**Comment by jaymores** [comment]
@KSY97 issues 에서 할일을 관리하고 readme.md에 관리하는것이 좋습니다.

커밋에는 이슈번호를 남겨주세요.

eg.) feat: flask 서버를 비동기 서버로 만들기 #4

**Comment by KSY97** [comment]
to do 리스트처럼 사용하는거군요!!
감사합니다!
